taps: []

packages:
  - { name: ansible, state: present}
  - { name: anyenv, state: present}
  - { name: aom, state: present}
  - { name: apr, state: present}
  - { name: apr-util, state: present}
  - { name: aspell, state: present}
  - { name: autoconf, state: present}
  - { name: automake, state: present}
  - { name: bash-completion, state: present}
  - { name: bento4, state: present}
  - { name: boost, state: present}
  - { name: brotli, state: present}
  - { name: c-ares, state: present}
  - { name: cairo, state: present}
  - { name: cfssl, state: present}
  - { name: cmake, state: present}
  - { name: coreutils, state: present}
  - { name: curl, state: present}
  - { name: dnsmasq, state: present}
  - { name: docker, state: present}
  - { name: docker-compose, state: present}
  - { name: docker-machine, state: present}
  - { name: ethereum, state: present}
  - { name: ffmpeg, state: present}
  - { name: flac, state: present}
  - { name: fontconfig, state: present}
  - { name: freetds, state: present}
  - { name: freetype, state: present}
  - { name: frei0r, state: present}
  - { name: fribidi, state: present}
  - { name: gd, state: present}
  - { name: gdbm, state: present}
  - { name: gdrive, state: present}
  - { name: gettext, state: present}
  - { name: ghostscript, state: present}
  - { name: giflib, state: present}
  - { name: git, state: present}
  - { name: git-lfs, state: present}
  - { name: glib, state: present}
  - { name: gmp, state: present}
  - { name: gnutls, state: present}
  - { name: go, state: present}
  - { name: gobject-introspection, state: present}
  - { name: graphicsmagick, state: present}
  - { name: graphite2, state: present}
  - { name: graphviz, state: present}
  - { name: gts, state: present}
  - { name: harfbuzz, state: present}
  - { name: icu4c, state: present}
  - { name: imagemagick, state: present}
  - { name: jansson, state: present}
  - { name: jasper, state: present}
  - { name: jbig2dec, state: present}
  - { name: jemalloc, state: present}
  - { name: jpeg, state: present}
  - { name: jq, state: present}
  - { name: lame, state: present}
  - { name: leptonica, state: present}
  - { name: libass, state: present}
  - { name: libbluray, state: present}
  - { name: libde265, state: present}
  - { name: libev, state: present}
  - { name: libevent, state: present}
  - { name: libffi, state: present}
  - { name: libheif, state: present}
  - { name: libiconv, state: present}
  - { name: libidn, state: present}
  - { name: libidn2, state: present}
  - { name: libmetalink, state: present}
  - { name: libogg, state: present}
  - { name: libomp, state: present}
  - { name: libpng, state: present}
  - { name: libpq, state: present}
  - { name: libsamplerate, state: present}
  - { name: libsndfile, state: present}
  - { name: libsoxr, state: present}
  - { name: libssh2, state: present}
  - { name: libtasn1, state: present}
  - { name: libtiff, state: present}
  - { name: libtool, state: present}
  - { name: libunistring, state: present}
  - { name: libvidstab, state: present}
  - { name: libvorbis, state: present}
  - { name: libvpx, state: present}
  - { name: libxml2, state: present}
  - { name: libxslt, state: present}
  - { name: libyaml, state: present}
  - { name: libzip, state: present}
  - { name: little-cms2, state: present}
  - { name: lzo, state: present}
  - { name: mas, state: present }
  - { name: maven, state: present}
  - { name: mitmproxy, state: present}
  - { name: mhash, state: present}
  - { name: mongoose, state: present}
  - { name: mosh, state: present}
  - { name: netpbm, state: present}
  - { name: nettle, state: present}
  - { name: nghttp2, state: present}
  - { name: nginx, state: present}
  - { name: nspr, state: present}
  - { name: nss, state: present}
  - { name: nvm, state: present }
  - { name: openconnect, state: present}
  - { name: opencore-amr, state: present}
  - { name: openexr, state: present}
  - { name: openjpeg, state: present}
  - { name: openldap, state: present}
  - { name: openssl, state: present}
  - { name: opus, state: present}
  - { name: p11-kit, state: present}
  - { name: p7zip, state: present}
  - { name: pcre, state: present}
  - { name: pcre2, state: present}
  - { name: pdftohtml, state: present}
  - { name: peco, state: present}
  - { name: php, state: present}
  - { name: pixman, state: present}
  - { name: pkg-config, state: present}
  - { name: protobuf, state: present}
  - { name: pstree, state: present}
  - { name: python, state: present}
  - { name: qt, state: present}
  - { name: readline, state: present}
  - { name: redis, state: present}
  - { name: rename, state: present}
  - { name: rtmpdump, state: present}
  - { name: rubberband, state: present}
  - { name: sbt, state: present}
  - { name: scrcpy, state: present}
  - { name: sdl2, state: present}
  - { name: shared-mime-info, state: present}
  - { name: snappy, state: present}
  - { name: socat, state: present}
  - { name: speex, state: present}
  - { name: sphinx-doc, state: present}
  - { name: sqlite, state: present}
  - { name: stoken, state: present}
  - { name: terraform, state: present}
  - { name: tesseract, state: present}
  - { name: theora, state: present}
  - { name: thrift, state: present}
  - { name: tidy-html5, state: present}
  - { name: tree, state: present}
  - { name: unar, state: present}
  - { name: unbound, state: present}
  - { name: unixodbc, state: present}
  - { name: webp, state: present}
  - { name: wget, state: present}
  - { name: x264, state: present}
  - { name: x265, state: present}
  - { name: xvid, state: present}
  - { name: xz, state: present}
  - { name: yarn, state: present}
