- name: homebrew cask install
  community.general.homebrew_cask:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    install_options: 'appdir=/Applications'
  loop: "{{ packages }}"
  ignore_errors: yes
  tags:
    - homebrew_cask
