- block:

  - name: homebrew cask install

    community.general.homebrew_cask:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
      install_options: 'appdir=/Applications'
    with_items: "{{ packages }}"

  tags:
    - homebrew_cask
