packages:
  - { name: 1Password, state: present }
  - { name: abstract, state: present }
  - { name: adobe-acrobat-reader, state: present }
  - { name: alfred, state: present }
  - { name: amazon-music, state: present }
  - { name: android-studio, state: present }
  - { name: appcleaner, state: present }
  - { name: atom, state: present }
  - { name: betterzipql, state: present }
  - { name: brave-browser, state: present }
  - { name: caffeine, state: present }
  - { name: charles, state: present }
  - { name: chatwork, state: present }
  - { name: colorsnapper, state: present }
  - { name: coteditor, state: present }
  - { name: dash, state: present }
  - { name: deco, state: present }
  - { name: diffmerge, state: present }
  - { name: discord, state: present }
  - { name: divvy, state: present }
  - { name: docker, state: present }
  - { name: dropbox, state: present }
  - { name: eclipse-ide, state: present }
  - { name: ethereum-wallet, state: present }
  - { name: evernote, state: present }
  - { name: firefox, state: present }
  - { name: fluid, state: present }
  - { name: flux, state: present }
  - { name: ganache, state: present }
  - { name: google-chrome, state: present }
  - { name: google-web-designer, state: present }
  - { name: google-japanese-ime, state: present }
  - { name: hype, state: present }
  - { name: imagealpha, state: present }
  - { name: imageoptim, state: present }
  - { name: insomnia, state: present }
  - { name: intellij-idea, state: present }
  - { name: iota-wallet, state: present }
  - { name: iterm2, state: present }
  - { name: itsycal, state: present }
  - { name: kap, state: present }
  - { name: keepassx, state: present }
  - { name: kindle, state: present }
  - { name: licecap, state: present }
  - { name: macdown, state: present }
  - { name: mist, state: present }
  - { name: mongodb, state: present }
  - { name: near-lock, state: present }
  - { name: ngrok, state: present }
  - { name: notion, state: present }
  - { name: opera, state: present }
  - { name: pritunl, state: present }
  - { name: provisionql, state: present }
  - { name: qlcolorcode, state: present }
  - { name: quicklook-csv, state: present }
  - { name: quicklook-json, state: present }
  - { name: qlmarkdown, state: present }
  - { name: qlstephen, state: present }
  - { name: resolutionator, state: present }
  - { name: securid, state: present }
  - { name: sketch, state: present }
  - { name: Skitch, state: present }
  - { name: skype, state: present }
  - { name: slack, state: present }
  - { name: spotify, state: present }
  - { name: station, state: present }
  - { name: sublime-text, state: present }
  - { name: telegram, state: present }
  - { name: the-unarchiver, state: present }
  - { name: Tomato One, state: present }
  - { name: tower, state: present }
  - { name: townwifi, state: present }
  - { name: transmit, state: present }
  - { name: tunnelbear, state: present }
  - { name: tunnelblick, state: present }
  - { name: unity-hub, state: present }
  - { name: virtualbox, state: present }
  - { name: visual-studio-code, state: present }
  - { name: vivaldi, state: present }
  - { name: vlc, state: present }
  - { name: webponize, state: present }
  - { name: webstorm, state: present }
  - { name: wireshark, state: present }
  - { name: xampp, state: present }
  - { name: xmind, state: present }
  - { name: zeplin, state: present }
  - { name: zoomus, state: present }
  - { name: music-manager, state: present }
  - { name: vagrant, state: present }
