packages:
  - { name: 1Password, state: present }
  - { name: adobe-acrobat-reader, state: present }
  - { name: alfred, state: present }
  - { name: appcleaner, state: present }
  - { name: betterzip, state: present }
  - { name: bitwarden, state: present }
  - { name: blackhole-16ch, state: present }
  - { name: brave-browser, state: present }
  - { name: caffeine, state: present }
  - { name: charles, state: present }
  - { name: claude, state: present }
  - { name: clipy, state: present }
  - { name: cursor, state: present }
  - { name: deepl, state: present }
  - { name: deskpad, state: present }
  - { name: diffmerge, state: present }
  - { name: discord, state: present }
  - { name: docker, state: present }
  - { name: dropbox, state: present }
  - { name: figma, state: present }
  - { name: firefox, state: present }
  - { name: fluid, state: present }
  - { name: google-chrome, state: present }
  - { name: google-cloud-sdk, state: present }
  - { name: google-japanese-ime, state: present }
  - { name: hiddenbar, state: present }
  - { name: imageoptim, state: present }
  - { name: insomnia, state: present }
  - { name: iterm2, state: present }
  - { name: itsycal, state: present }
  - { name: jetbrains-toolbox, state: present }
  - { name: kap, state: present }
  - { name: keepassx, state: present }
  - { name: licecap, state: present }
  - { name: linear-linear, state: present }
  - { name: macdown, state: present }
  - { name: meetingbar, state: present }
  - { name: ngrok, state: present }
  - { name: notion, state: present }
  - { name: obs, state: present }
  - { name: opera, state: present }
  - { name: pritunl, state: present }
  - { name: provisionql, state: present }
  - { name: qlcolorcode, state: present }
  - { name: quicklook-csv, state: present }
  - { name: quicklook-json, state: present }
  - { name: qlmarkdown, state: present }
  - { name: qlstephen, state: present }
  - { name: rectangle, state: present }
  - { name: resolutionator, state: present }
  - { name: slack, state: present }
  - { name: sourcetree, state: present }
  - { name: spotify, state: present }
  - { name: sublime-text, state: present }
  - { name: telegram, state: present }
  - { name: the-unarchiver, state: present }
  - { name: tunnelbear, state: present }
  - { name: tunnelblick, state: present }
  - { name: unity-hub, state: present }
  - { name: virtualbox, state: present }
  - { name: visual-studio-code, state: present }
  - { name: vivaldi, state: present }
  - { name: vlc, state: present }
  - { name: xmind, state: present }
