- block:

  - name: homebrew update/upgrade
    homebrew:
      update_homebrew: true
      upgrade_all: yes

  - name: homebrew tap
    homebrew_tap:
      name: "{{ item }}"
      state: present
    loop: "{{ taps }}"

  - name: homebrew install
    homebrew:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop: "{{ packages }}"

  tags:
    - homebrew
